---
title: "HPBBM2023"
author: 
  - name: Modesto
    affiliation: Department of Biochemistry, UAM
    affiliation_url: https://www.uam.es/
  - name: Luis
    affiliation: Department of Biochemistry, UAM
    affiliation_url: https://www.uam.es/
    email: luis.peso@uam.es
date: "May 30, 2023"
date-modified: "`r format(Sys.time(), '%Y-%m-%d (%H:%M h)')`"
categories: 
  - R
  - RStudio
  - Data analysis
  - R for Biochemists
format: 
  html:
    page-layout: full
toc: true
toc-location: left
toc-depth: 2
number-sections: true
number-depth: 1
code-overflow: wrap
link-external-icon: true
link-external-newwindow: true 
editor: visual
---
```{r}

```

> There are only two kinds of programming languages: the ones people complain about and the ones nobody uses. ---*Bjarne Stroustrup*

## [Wellcome & Disclaimer]{style="color:darkblue"}

::: callout-warning
## Under construction, note that it can be updated during the Course
:::

::: {style="float: right; position: relative; top: 0px; padding: 3px;"}
![Logo generated with hexSticker package.[^1]](HPBBM2023.png){width="228"}
:::

[^1]: See the code in the script *r_sticker.R* in the repo.



This site contains the materials for the *Coding tools for Biochemistry & Molecular Biology* (Herramientas de Programación para Bioquímica y Biología Molecular, a.k.a. **HPBBM**) course of **fall 2023** in the Bachelor's Degree in Biochemistry \@[UAM](www.uam.es) (Universidad Autónoma de Madrid, Spain). Source files are available at the [{{< bi github >}} repo](https://github.com/mredrejo/HPBBM2023), containing the source files and the data used in the examples and exercises. The icon [{{< bi cloud-download >}}](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mredrejo/HPBBM2022/tree/main/data) on the top-right corner in all the site pages will allow you to download the repo **data** folder (link generated with [DownGit](https://yehonal.github.io/DownGit/#/home)). Note that this folder can be updated during the course. For reference, materials from **2022** course edition are available in the [HPBBM2022 site](https://mredrejo.github.io/HPBBM2022/).

Course Syllabus can be checked at [UAM site](https://secretaria-virtual.uam.es/doa/consultaPublica/look%5Bconpub%5DMostrarPubGuiaDocAs) and a PDF version is available [here](HPBBM_syllabus2023.pdf). The course contains a first block of lessons on Python programming (Lessons 1-7) that is not included here. Detailed academic information about the course contents, dates, and assessment only can be found at the [UAM Moodle site](https://moodle.uam.es/). In this site, the lessons pages have been generated as *Quarto* to obtain source files (*.qmd*) that contain formatted text and chunks of R code that are executed upon rendering (see [lesson R7](r7.html) for more info about Markdown and Quarto in RStudio). 

::: callout-tip
# How to use this site
These materials have been designed as an interactive and self-learning resource. As you go through the lessons, think about the code beforehand and then test it with your computer. Then try out the exercises for yourself. 

You can consult the references for additional examples or help and also ask the instructor in the on-site classes.
:::

::: callout-caution
# Update R and RStudio
All the Lessons contain a final *R Session info* where you can see the used versions for R and all packages. 
Anyway, espacially if you installed R in your computer for the first time some years ago, I kindly request to **update** R and RStudio before going forward.
:::

Lessons also contain embedded interactive [short exercises]{style="color:darkseagreen"} (generated with [`learnr`](https://rstudio.github.io/learnr/) y/o [`webexercises`](https://psyteachr.github.io/webexercises/articles/webexercises.html) packages). Try them before checking the proposed solution. Also, we included a final section of [*Review exercises*]{style="color:darkgreen"}, some of them from freely available online solved exercises and others that we created. The answers to the latter are not available online, but I'll be glad to provide them upon request.

All this material is open access and it is shared under [CC BY-NC](https://creativecommons.org/licenses/by-nc/2.0/) license.

This is a draft version of this site, but it is intended to be expanded and corrected throughout the next weeks and new versions will be available the following years. Any feedback, help, or suggestions will be very warmly welcome.

Also, it is likely that you find some mistypes or even some big mistakes throughout these course materials. I, and the future students, will appreciate it if you let me know about anything that could be corrected or just improved. You can reach us by [email](mailto::modesto.redrejo@uam.es).

## [Bibliography and Resources]{style="color:darkblue"}

Each lesson contains its own specific references, but we wanted to highlight here some curated general open access and open source resources to introduce yourself into R and R Studio.

-   Grolemund, G. [*Hands-on Programming in R*](https://rstudio-education.github.io/)*.*

-   Peng, R. D. R [*Programming for Data Science.*](https://bookdown.org/rdpeng/rprogdatascience/)

-   Coulatti, R. I. [*R Crash Course for Biologist*.](https://github.com/ColauttiLab/RCrashCourse_Book)

-   Chang, W. R. [R Graphics Cookbook.](https://r-graphics.org/)

-   Doyle, M., Chung, J. & Perreau V. [Introduction to R for Biologists.](https://melbournebioinformatics.github.io/r-intro-biologists/intro_r_biologists.html)

-   [Learn R by example](https://www.learnbyexample.org/r/)

-   [R base cheatsheet](https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf)

-   [R programming 101 @YouTube](https://www.youtube.com/@RProgramming101)

## [Contents]{style="color:darkblue"}
### [Lesson R1: Variables, Operators and data structures in R](r1.html)

### [Lesson R2: Flow Control](r2.html)

### [Lesson R3: Data input and output in R](r3.html)

### [Lesson R4: Write your own functions](r4.html)

### [Lesson R5: Plots](r5.html)

### [Lesson R6: Data management](r6.html)

### [Lesson R7: R-projects and R-markdown for reproducible data analysis](r7.html)

### [Lesson R8: Advanced data plotting with `ggplot`](r8.html)

### [Lesson R9: Applications for Molecular Biology](r9.html)
